name: isd_tms
description: "Task Management System"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.7 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  equatable: ^2.0.5

  # DI
  get_it: ^7.7.0

  # Network
  dio: ^5.4.1
  pretty_dio_logger: ^1.4.0
  internet_connection_checker: ^1.0.0+1

  # Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2

  # UI & Theme
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0
  lottie: ^3.1.0
  quill_html_editor:
    git:
      url: https://github.com/the-airbender/quill_html_editor.git
      ref: a171f44

  # Localization
  intl: ^0.20.2

  # Annotations
  freezed_annotation: ^3.1.0
  freezed: ^3.2.5
  json_annotation: ^4.8.1

  # Firebase & Notifications
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.10
#  flutter_local_notifications: ^17.0.0
  image_picker: ^1.2.1
  flutter_image_compress: ^2.3.0
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  retrofit: ^4.9.2
  retrofit_generator: ^10.2.3
  quick_log: ^5.5.3
  file_picker: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  # Dev Tools
  build_runner: ^2.13.1
  flutter_gen_runner: ^5.13.0+1
  hive_ce_generator: ^1.11.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - lang/
    - assets/images/
    - assets/icons/
    - assets/lottie/

  fonts:
    - family: Public Sans
      fonts:
        - asset: assets/fonts/PublicSans-Light.ttf
          weight: 300
        - asset: assets/fonts/PublicSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PublicSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/PublicSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PublicSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PublicSans-Bold.ttf
          weight: 700
