import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:isd_tms/src/core/di/dependency_injection.dart';
import 'package:isd_tms/src/core/helpers/bloc_observer.dart';
import 'package:isd_tms/src/core/helpers/hive/hive_initializer.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:isd_tms/src/root/app.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);
  await ScreenUtil.ensureScreenSize();
  // Initialize Firebase (Assuming firebase_options.dart is generated by FlutterFire CLI)
  // If not generated, user will need to add it later.
  // try {
  //   // await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  //   await Firebase.initializeApp();
  // } catch (e) {
  //   printMe('FireBase Initial Error: $e');
  // }
  Bloc.observer = MyBlocObserver();
  await DependencyInjection.init();
  await HiveInitializer.init();
  runApp(const IsdTmsApp());
}
